name: Submit use case for Build-a-thon 2023
description: Submit use case related text for Build-a-thon 2023
title: "[Submit use case for Build-a-thon 2023]: "
labels: ["Submit use case for Build-a-thon 2023"]
assignees:
  - vrra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit use case for Build-a-thon 2023!
        CAUTION: make sure you are registered first here https://github.com/vrra/FGAN-Build-a-thon/issues/new/choose
  - type: dropdown
    id: team-name
    attributes:
      label: Team name
      multiple: false
      options: 
      - "CR-Insight"
    validations:
      required: true
  - type: input
    id: Use-case-Text
    attributes:
      label: Use case Text
      description: Enter use case text here
      placeholder: ex. A closed loop module collect real-time data from the 4/5G integrated network management, then compares the consistency of the number of network elements from the data, and displays data quality monitoring and warning through the visualization panel.
    validations:
      required: true
  - type: input
    id: Reference
    attributes:
      label: Reference (if any)
      description: Enter details of any reference document
      placeholder: ex. https://www.itu.int/rec/T-REC-Y.Sup71-202207-I 
    validations:
      required: false
