name: Submit use case for Build-a-thon 2023
description: Submit use case related text for Build-a-thon 2023
title: "[Submit use case for Build-a-thon 2023]: "
labels: ["Submit use case for Build-a-thon 2023"]
assignees:
  - vrra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit use case for Build-a-thon 2023!
        CAUTION: make sure you are registered first here https://github.com/vrra/FGAN-Build-a-thon/issues/new/choose
  - type: dropdown
    id: team-name
    attributes:
      label: Team name
      multiple: false
      options: 
      - "CR-Insight"
      - "CR-Analytics"
      - "Nokia Champ"
      - "Perfect Unit"
      - "TECH CREED"
      - "Acute Angle"
      - "Attack on Hackers"
    validations:
      required: true
  - type: input
    id: Filename
    attributes:
      label: Filename
      description: Enter Filename here
      placeholder: e.g. Use-case-AN.pdf
    validations:
      required: true
  - type: input
    id: URL
    attributes:
      label: URL
      description: Enter the URL to access the file
      placeholder: e.g. https://www.itu.int/en/ITU-T/focusgroups/an/Documents/Use-case-AN.pdf
    validations:
      required: true
