name: sample1
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  issues: 
    types: [opened, edited]
    
jobs:
  issue_opened_edited:
    runs-on: ubuntu-latest
    steps:
      - name: print issue details
        run: |
          echo Gotcha issue $LABELS
        env:
          LABELS: ${{ github.event.issue.labels[0].name }}   
      - name: print secret and variables
        uses: actions/checkout@v2
        with:
            repository: vrra/FGAN-Build-a-thon
            token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: print env vars
        run: |
          run: python ${{ vars.SCRIPTS_DIR }}/PushRecordToArgilla-HF.py
          shell: sh
        env:
            API_URL: ${{ vars.API_URL }}
            API_KEY: ${{ secrets.API_KEY }}
            ARGILLA_WORKSPACE: ${{ secrets.ARGILLA_WORKSPACE }}
            VISHNURAMOV_PUSH_TO_HF_HUB_TOKEN: ${{ secrets.VISHNURAMOV_PUSH_TO_HF_HUB_TOKEN }}        