name: sample1
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  issues: 
    types: [opened, edited]
    
jobs:
  issue_opened_edited:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: |
          echo Gotcha issue $LABELS
        env:
          LABELS: ${{ github.event.issue.labels[0].name }}   

      - name: Checkout so that we have the python script in the container
        uses: actions/checkout@v2
        with:
            repository: vrra/FGAN-Build-a-thon
            token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: View the github context
        run: echo "$GITHUB_CONTEXT" >> ${{ vars.SCRIPTS_DIR }}/issue.out
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Push to Argilla
        run: python ${{ vars.SCRIPTS_DIR }}/PushRecordToArgilla-HF.py
        shell: sh
        env:
            API_URL: ${{ vars.API_URL }}
            API_KEY: ${{ vars.API_KEY }}
            ARGILLA_WORKSPACE: ${{ vars.ARGILLA_WORKSPACE }}
            VISHNURAMOV_PUSH_TO_HF_HUB_TOKEN: ${{ vars.VISHNURAMOV_PUSH_TO_HF_HUB_TOKEN }}        