name: sample1
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  issues: 
    types: [opened, edited]
jobs:
  issue_opened_edited:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Gotcha issue $name
        env:
          name: ${{ github.event.issue.labels.name }}
